FROM node:8

ENV NODE_ENV dev
RUN mkdir -p /usr/app/front
WORKDIR /usr/app/front

COPY public /usr/app/front/public
COPY package.json /usr/app/front
COPY server.js /usr/app/front

RUN cd /usr/app/front && npm install --only=production

CMD npm run server:prod