version: "3.3"

services:
  web:
    build: ./Frontend
    ports:
      - 8080:8080
    depends_on: 
      - back
  back:
    build: ./Backend
    ports:
      - 8083:8083
    depends_on: 
      - cms
    environment: 
      - CMS=http://cms:1337
      - PORT=8083
      - FRONT=http://localhost:8081
  cms:
    build: ./cms
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - type: bind
        source: "./cms/api"
        target: /usr/src/api/strapi-app/api
      - upload:/usr/src/api/strapi-app/public/uploads
    depends_on:
      - mongo    
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    restart: always
    
volumes:
  mongodb:
  upload: