version: '3'

services:
  web:
    build: ./Frontend
    ports:
      - 8080:8080
    depends_on: 
      - back
  back:
    build: ./Backend
    ports:
      - 8081:8081
    environment: 
      STRAPI: http://dev06:1337
