FROM node:9.11.1-alpine

WORKDIR /usr/src/api

RUN npm install -g strapi@3.0.0-alpha.14

COPY strapi.sh /
COPY api /usr/src/api/files
RUN chmod +x /strapi.sh

EXPOSE 1337

COPY healthcheck.js /
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s \
      CMD node /usr/src/api/healthcheck.js

CMD ["/strapi.sh"]
