FROM node:9.11.1-alpine

ENV NODE_ENV development
RUN mkdir -p /usr/src/cms
WORKDIR /usr/src/cms

COPY . /usr/src/cms
RUN npm install -g strapi@3.0.0-alpha.14
RUN cd /usr/src/cms && npm install

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && strapi start